### ISSUE TITLE
Error in node when using Grunt

### ISSUE THREAD

**Issue by fierwebdesign** [cniska/yii-app#13]
Following the install instructions I get an error when using grunt.

grunt --help

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'existsSync'
    at Object.exists (/var/www/yii-app/node_modules/grunt/lib/grunt/file.js:372:13)
    at Task.init (/var/www/yii-app/node_modules/grunt/lib/grunt/task.js:417:31)
    at Object.initTasks (/var/www/yii-app/node_modules/grunt/lib/grunt/help.js:90:14)
    at /var/www/yii-app/node_modules/grunt/lib/grunt/help.js:49:54
    at Array.forEach (native)
    at Object.display (/var/www/yii-app/node_modules/grunt/lib/grunt/help.js:49:17)
    at Object.tasks (/var/www/yii-app/node_modules/grunt/lib/grunt.js:101:10)
    at Object.cli (/var/www/yii-app/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/usr/lib/node_modules/grunt-cli/bin/grunt:36:20)
    at Module._compile (module.js:432:26)

I tried updating node, but this does not seem to help. What am I missing / doing wrong?

**Comment by fierwebdesign** [comment]
Problem solved. I somehow needed an update of node.
